# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yCmSHEPlzNVzqHdxS3W4epkBiY35aX85
"""

!pip install groq numpy

import os
from groq import Groq
client = Groq()

from groq import Groq

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

docs = [
    "Python is a programming language",
    "RAG means Retrieval Augmented Generation",
    "Streamlit is used for web apps"
]

def retrieve(query):
    for doc in docs:
        if query.lower() in doc.lower():
            return doc
    return docs[0]

query = "What is RAG?"

context = retrieve(query)

response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[
        {"role": "user", "content": f"Answer using this context: {context}\n\nQuestion: {query}"}
    ]
)

print(response.choices[0].message.content)

!pip install streamlit

import streamlit as st
from groq import Groq

client = Groq()

st.title("RAG Chatbot")

user_input = st.text_input("Ask something")

docs = [
    "Python is a programming language",
    "RAG means Retrieval Augmented Generation",
    "Streamlit is used for web apps"
]

def retrieve(query):
    for doc in docs:
        if query.lower() in doc.lower():
            return doc
    return docs[0]

if user_input:
    context = retrieve(user_input)

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {"role": "user", "content": f"{context}\nQuestion: {user_input}"}
        ]
    )

    st.write(response.choices[0].message.content)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# from groq import Groq
# 
# client = Groq()
# 
# st.title("RAG Chatbot")
# 
# user_input = st.text_input("Ask something")
# 
# docs = [
#     "Python is a programming language",
#     "RAG means Retrieval Augmented Generation",
#     "Streamlit is used for web apps"
# ]
# 
# def retrieve(query):
#     for doc in docs:
#         if query.lower() in doc.lower():
#             return doc
#     return docs[0]
# 
# if user_input:
#     context = retrieve(user_input)
# 
#     response = client.chat.completions.create(
#         model="llama-3.1-8b-instant",
#         messages=[
#             {"role": "user", "content": f"{context}\nQuestion: {user_input}"}
#         ]
#     )
# 
#     st.write(response.choices[0].message.content)

!pip install streamlit pyngrok

!pip install streamlit pyngrok

from pyngrok import ngrok

ngrok.set_auth_token("")

!ls

!streamlit run app.py &>/dev/null&

public_url = ngrok.connect(8501)
print("OPEN THIS:", public_url)